[package]
name = "silkroad-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
serde = "1"
serde_derive = "1"
lazy_static = "1.4"
tracing = "0.1"
log = { version = "*", default-features = false }
chrono = "0.4"
crossbeam-channel = "0.5"
tokio = { version = "1", features = ["full"] }
tokio-util = "*"
tracing-subscriber = "0.3"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-tokio-native-tls", "postgres", "macros", "uuid", "chrono" ] }
silkroad-network = { path = "../silkroad-network" }
silkroad-protocol = { path = "../silkroad-protocol" }
silkroad-rpc = { path = "../silkroad-rpc" }
silkroad-security = { path = "../silkroad-security" }
reqwest = { version = "*", features = ["json"] }
