[workspace]
members = [
    "silkroad-network",
    "silkroad-codegen",
    "silkroad-protocol",
    "silkroad-gateway",
    "silkroad-rpc",
    "silkroad-security",
    "silkroad-agent",
    "silkroad-navmesh",
    "silkroad-navmesh-viewer",
    "silkroad-data",
    "silkroad-packet-decryptor"
]

[profile.dev]
opt-level = 1