[workspace]
members = [
    "silkroad-network",
    "silkroad-protocol",
    "silkroad-gateway",
    "silkroad-rpc",
    "silkroad-security",
    "silkroad-agent",
    "silkroad-navmesh",
    "silkroad-serde",
    "silkroad-serde-derive",
    "silkroad-data",
    "silkroad-packet-decryptor"
]

[workspace.dependencies]
tokio = { version = "1.16.1", features = ["full"] }
once_cell = "1.13.0"
byteorder = "1.4.3"
rand = "0.8.4"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
config = "0.13.2"
log = "0.4.17"
thiserror = "1.0.32"
chrono = "0.4.22"
bytes = "1.2.1"
serde = "1.0.144"
serde_derive = "1.0.144"
sqlx = { version = "0.6.2", default-features = false, features = ["runtime-tokio-native-tls", "postgres", "macros", "uuid", "chrono"] }

[profile.dev]
opt-level = 1