[package]
name = "silkroad-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
silkroad-serde = { path = "../silkroad-serde" }
silkroad-serde-derive = { path = "../silkroad-serde-derive" }