[package]
name = "silkroad-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
silkroad-serde-derive = { path = "../silkroad-serde-derive" }
chrono = "0.4.19"
paste = "1"
byteorder = "1"
thiserror = "1.0"
