[package]
name = "silkroad-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { workspace = true }
silkroad-network = { path = "../silkroad-network" }
silkroad-protocol = { path = "../silkroad-protocol" }
silkroad-rpc = { path = "../silkroad-rpc" }
silkroad-navmesh = { path = "../silkroad-navmesh", features = ["pk2"] }
silkroad-data = { path = "../silkroad-data" }
tokio = { workspace = true }
axum = "0.5.13"
bytes = "1.1.0"
once_cell = { workspace = true }
byteorder = { workspace = true }
rand = { workspace = true }
crossbeam-channel = "0.5.2"
tracing = { workspace = true }
config = { workspace = true }
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-native-tls", "postgres", "macros", "uuid", "chrono"] }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
itertools = "*"
bevy_ecs = "0.7.0"
bevy_ecs_macros = "0.7.0"
bevy_core = "0.7.0"
bevy_app = "0.7.0"
bevy_tasks = "0.7.0"
cgmath = "0.18.0"
pk2 = "0.1.0"
id-pool = { version = "0.2.1", features = ["u32"], default_features = false }