agent-healthcheck-interval = 5

[patch]
remote-url = "localhost/"
dir = "./patch-files"
accept-all = true
expected-client-version = 594
minimum-client-version = 592

[database]
host = "localhost"
user = "skrillax"
password = "skrillax"
database = "skrillax"